serverAddr = "127.0.0.1"
serverPort = 7000
# Heartbeat
transport.heartbeatInterval = 30
transport.heartbeatTimeout = 90

# Transport
transport.tcpMux = true
transport.useCompression = true
transport.useEncryption = true
transport.poolCount = 10
transport.dialServerKeepalive = 20


[[proxies]]
name = "my-tunnel"
type = "tcp"
localIP = "0.0.0.0"
localPort = 6000
remotePort = 6009