serverAddr = "43.159.166.153"
serverPort = 20073

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

loginFailExit = false

[[proxies]]
name = "tester"
type = "tcp"
localIP = "127.0.0.1"
localPort = 6000
remotePort = 6000
