serverAddr = "sjc1.clusters.zeabur.com"
serverPort = 20073

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

loginFailExit = false

[[proxies]]
name = "tester"
type = "tcp"
localIP = "0.0.0.0"
localPort = 6000
remotePort = 6000
useEncryption = true