serverAddr = "sjc1.clusters.zeabur.com"
serverPort = 20073

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

loginFailExit = false
transport.poolCount = 10
transport.heartbeatTimeout = 90
transport.heartbeatInterval = 30

[[proxies]]
name = "test"
type = "tcp"
localIP = "127.0.0.1"
localPort = 6000
remotePort = 6000
